sudo: required
services:
  - docker

before_install:
  - docker build -t codecroze/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true  codecroze/react-test npm test -- --coverage

after_success:
  - docker build -t codecroze/multi-client ./client
  - docker build -t codecroze/multi-nginx ./nginx
  - docker build -t codecroze/multi-server ./server
  - docker build -t codecroze/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login  -u "$DOCKER_ID" --password-stdin 
  - docker push codecroze/multi-client
  - docker push codecroze/multi-nginx
  - docker push codecroze/multi-server
  - docker push codecroze/multi-worker
